#!/bin/bash
# Created by jlchen at 03/03/2016 08:30:45 PM 
## List all the free pbsnodes which have no running jobs, aka, completely free.
## 
echo "# Question to jlchen chen@ipp.ac.cn"
echo "Only completely free nodes are listed below:"
echo -e "nodes \t\t cores \t queue"
pbsnodes -l free | grep -o "shenma[0-9]\+" | while read shenmanodes 


do
    if test -n "$(pbsnodes $shenmanodes | grep -o 'jobs=,')"; then
	cores_num="$(pbsnodes $shenmanodes | grep 'np = ' | grep -o '[0-9]*')"
        shenmaID_num=$(pbsnodes $shenmanodes | grep -o -e "uname=Linux shenma[0-9][0-9][0-9]"|grep -o -e "[0-9][0-9][0-9]")
     #   echo $shenmaID_num
	if [[ ${shenmaID_num:0:1} -eq 0 ]] ; then
		shenmaID_num=${shenmaID_num:1}
		if [[  ${shenmaID_num:0:1} -eq 0 ]] ; then
			shenmaID_num=${shenmaID_num:1}
		fi
	fi
    #    echo $shenmaID_num
        if [[ $shenmaID_num -gt 100 && $shenmaID_num -lt 111 ]] ; then
            queue_type='batch'
        else
            if [[ $shenmaID_num -gt 110 ]] ; then
                queue_type='parallel11'
            else 
                queue_type='parallel01'
            fi
        fi
        echo -e "$shenmanodes \t $cores_num \t $queue_type"
    fi
done
##########



